% This is a script to generate the log-log graph from the text file
% generated from problem_1.cpp
%
% Written By- SHOWREN DATTA
% Last Modified On- September 14th, 2020
%**************************************************************************
clear;

% Loading data from problem_1.txt generated by problem_1.cpp
data = load ('problem_1.txt');

% Collecting corresponding data of del_t and absolute_value
del_t = data (:,1);
absolute_error = data (:,2);


% Plotting the log-log graph and saving it as a png file
loglog(del_t,absolute_error,'*');
box on;
xlabel('\Deltat','Fontsize',12);
ylabel('\delta(\Deltat)','Fontsize',12);
title('Absolute Error \delta(\Deltat) v/s \Deltat for x(t) = 1 / (1 + 9 * exp(-t)) and t = 2');
saveas(gcf,'Problem_1_CPP','png');

